server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true #开启aop
  rabbitmq:
    host:
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名映射

#rabbitMq